sonar.projectKey=python-argo-kops
sonar.projectName=python-argo-kops-project
sonar.projectVersion=1.0
sonar.sources=app
sonar.language=py
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.md
